---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: netology
spec:
  replicas: 3
  selector:
    matchLabels:
      app: netology
  template:
    metadata:
      labels:
        app: netology
    spec:
      containers:
      - name: app-demo
        image: cr.yandex/crppqi6tfv23hnubsg5t/demo_app:0.0.5
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
  labels:
    app: netology
spec:
  type: LoadBalancer
  selector:
    app: netology
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80