# Файл: .github/workflows/yc-infra.yml

name: Change Infa
on:
  push:
    branches:
      - main  
jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.x
          
      - name: Install YC CLI
        run: |
          curl -s https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "$HOME/bin" >> $GITHUB_PATH
          echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH

      - name: Install kubectl
        run: |
          curl -LO https://dl.k8s.io/release/`curl -LS https://dl.k8s.io/release/stable.txt`/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          mv ./kubectl $HOME/bin/kubectl
          kubectl version --client
          
      # Добавить 
      - name: Create auth file
        env:
          YC_AUTH_KEY: ${{ secrets.YC_TOKEN }}
          SSH_KEY_PUB: ${{ secrets.SSH_KEY }}
        run: |
          echo $YC_AUTH_KEY > $HOME/authorized_key.json
          echo $SSH_KEY_PUB > $HOME/id_ed25519.pub
          yc config profile create sa
          yc config profile activate sa
          yc config set token $HOME/authorized_key.json
    
      - name: Deploy Infrastructure
        env:
          TF_VAR_region: ${{ secrets.TF_VAR_REGION }}
          TF_VAR_folder_id: ${{ secrets.TF_VAR_FOLDER_ID }}
          TF_VAR_cloud_id: ${{ secrets.TF_VAR_CLOUD_ID }}
          TF_VAR_sa_id: ${{ secrets.TF_VAR_SA_ID }}
          TF_VAR_storage_id: ${{ secrets.TF_VAR_STORAGE_ID }}
          TF_VAR_static_id_key: ${{ secrets.TF_VAR_STATIC_ID_KEY }}
          TF_VAR_static_access_key: ${{ secrets.TF_VAF_STATIC_ACCESS_KEY }}
          TF_VAR_static_secret_key: ${{ secrets.TF_VAR_STATIC_SECRET_KEY }}
        run: |
          export TF_VAR_auth_file="$HOME/authorized_key.json"
          export TF_VAR_ssh_key_file="$HOME/id_ed25519.pub"
          terraform -chdir=infra init -backend-config="access_key=$TF_VAR_static_access_key" -backend-config="secret_key=$TF_VAR_static_secret_key" -backend-config="bucket=$TF_VAR_storage_id" -reconfigure
          terraform -chdir=infra init
          terraform -chdir=infra plan
          terraform -chdir=infra apply -auto-approve
