# Файл: .github/workflows/yc-infra.yml

name: Change Infa
on:
  push:
    branches:
      - main  
jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.x
          
      - name: Install YC CLI
        run: |
          curl -s https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "$HOME/bin" >> $GITHUB_PATH
          echo "$HOME/yandex-cloud/bin" >> $GITHUB_PATH
      # Добавить 
      - name: Create auth file
        env:
          YC_AUTH_KEY: ${{ secrets.YC_TOKEN }}
          SSH_KEY_PUB: ${{ secrets.SSH_KEY }}
        run: |
          echo $YC_AUTH_KEY > authorized_key.json
          echo $SSH_KEY_PUB > id_ed25519.pub
    
      - name: Deploy Infrastructure
        env:
          TF_VAR_auth_file: "authorized_key.json"
          TF_VAR_region: ${{ secrets.TF_VAR_REGION }}
          TF_VAR_folder_id: ${{ secrets.TF_VAR_FOLDER_ID }}
          TF_VAR_cloud_id: ${{ secrets.TF_VAR_CLOUD_ID }}
          TF_VAR_sa_id: ${{ secrets.TF_VAR_SA_ID }}
          TF_VAR_storage_id: ${{ secrets.TF_VAR_STORAGE_ID }}
          TF_VAR_ssh_key_file: "id_ed25519.pub"

        run: |
          terraform -chdir=infra init
          terraform -chdir=infra plan
          terraform -chdir=infra apply -auto-approve
