# Файл: .github/workflows/terraform.yml

name: Terraform Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: env
    steps:
    # Установка необходимых зависимостей
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq python3-pip
        
    # Установка Terraform
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.x
        
    # Установка Yandex Cloud CLI
    - name: Install Yandex Cloud CLI
      run: |
        curl -s https://storage.yandexcloud.net/yandexcloud-yc/install.sh -o ./install.sh
        bash ./install.sh -i ~/
        export PATH="$PATH:$HOME/bin"
        
    # Добавить 
    - name: Add yc to PATH
      env:
        YC_AUTH_KEY: ${{ secrets.YC_TOKEN }}
      run: |
        echo $YC_AUTH_KEY > $HOME/authorized_key.json
        
    # Авторизация в Yandex Cloud
    - name: Authenticate with Yandex Cloud
      run: |
        export PATH="$PATH:$HOME/bin"
        yc config profile create deploy
        yc config set service-account-key $HOME/authorized_key.json
        
    # Клонирование репозитория
    - name: Checkout code
      uses: actions/checkout@v3
      
    # Запуск bash-скрипта
    - name: Run Terraform script
      env:
        TF_VAR_region: ${{ secrets.TF_VAR_REGION }}
        TF_VAR_folder_id: ${{ secrets.TF_VAR_FOLDER_ID }}
        TF_VAR_cloud_id: ${{ secrets.TF_VAR_CLOUD_ID }}
      run: |
        export PATH="$PATH:$HOME/bin"
        chmod +x ./terraform-deploy.sh
        ./terraform-deploy.sh -a $HOME/authorized_key.json -f $TF_VAR_folder_id -c $TF_VAR_cloud_id
